INSERT INTO users VALUES (1,'t','ADMIN','test');

INSERT INTO positionInReference (positionInReference) VALUES ('5''-promotor'), ('5''-untranslated region'), ('3''-untranslated region'), ('5''-exon'), ('3''-exon'), ('5''-intron'), ('3''-intron'), ('5''-enhancer'), ('5''-up'), ('3''-dw')
INSERT INTO purificationMethod (purificationMethod) VALUES ('Desalted'), ('Cartridge'), ('HPLC'), ('HPLC X'), ('PAGE')
INSERT INTO freezer (freezer) VALUES ('freezer1'), ('freezer2'), ('freezer3'), ('freezer4'), ('freezer5')
INSERT INTO drawer (drawer) VALUES ('drawer1'), ('drawer2'), ('drawer3'), ('drawer4'), ('drawer5')
INSERT INTO box (box) VALUES ('box1'), ('box2'), ('box3'), ('box4'), ('box5')
INSERT INTO organism (organism) VALUES ('Escherichia coli TG1'), ('Escherichia coli WK6'), ('Homo sapiens'), ('Mus musculus'), ('Rattus norvegicus domestica'), ('Other')
INSERT INTO humanGenomBuild (humanGenomBuild) VALUES ('NCBI Build 34'), ('NCBI Build 35'), ('NCBI Build 36.1'), ('GRCh37'), ('GRCh38')
INSERT INTO formulation (formulation) VALUES ('Lyophilized'), ('Water'), ('Resuspended in TRIS'), ('Resuspended in 1x TE'), ('Resuspended in 0,1 X TE'), ('Other')
INSERT INTO typeOfPrimer (typeOfPrimer) VALUES ('GAPDH primer'), ('M13 primer'), ('M13/pUC primer'), ('miRNA primer'), ('DNA/RNA probe'), ('TaqProbe'), ('Random primer'), ('Oligo dT'), ('RNA probes'), ('SP6 probes'), ('T3 primer'), ('T7 primer'), ('Gene Specific primer'), ('Diseas Specific primer'), ('Region Specific primer'), ('Gene Fusion primer'), ('Break Apart primer'), ('Chromosome Control primer')
INSERT INTO primerApplication (primerApplication) VALUES ('Genotyping'), ('Cloning'), ('NGS Sequencing'), ('Sanger Sequencing'), ('Bisulfite converted'), ('cDNA synthesis'), ('RT-qPCR-SYBR'), ('RT-qPCR-TaqMan'), ('PCR'), ('ddPCR'), ('Methylation-specific PCR'), ('In situ hybridisation'), ('FISH '), ('ChIP'), ('Flow Cytometry'), ('Other')

INSERT INTO primers (name, sequence, orientation, length, freezer_id, drawer_id, box_id, positionInReference_id, Tm, OptimalTOfAnnealing, purificationMethod_id, amountAvailableMikroL, amountAvailablePacks, amountAvailablePackSize, date, lengthOfAmplicone, storingT, GCPercent, organism_id, gen, ncbiGenId, humanGenomBuild_id, formulation_id, typeOfPrimer_id, sondaSequence, assayId, size, primerApplication_id) VALUES ('testname', 'testsequence', 1, 42, (SELECT id FROM freezer WHERE freezer = 'freezer2'), (SELECT id FROM drawer WHERE drawer = 'drawer5'), (SELECT id FROM box WHERE box = 'box1'), (SELECT id FROM positionInReference WHERE positionInReference = '5''-intron'), 24, 53, (SELECT id FROM purificationMethod WHERE purificationMethod = 'Cartridge'), 42.3, 28, 1, '12-31-2019', 4251, 324.2, 32.9, (SELECT id FROM organism WHERE organism = 'Mus musculus'), 'gen123', 'ncbiGenId42', (SELECT id FROM humanGenomBuild WHERE humanGenomBuild = 'GRCh37'), (SELECT id FROM formulation WHERE formulation = 'Resuspended in 0,1 X TE'), (SELECT id FROM typeOfPrimer WHERE typeOfPrimer = 'T7 primer'), 'SondaSequence123', 'assayId24', 3, (SELECT id FROM primerApplication WHERE primerApplication = 'Methylation-specific PCR'))